[project]
name = "shopify-django-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.6",
    "google-cloud-pubsub>=2.28.0",
    "shopifyapi>=12.7.0",
    "python-dotenv>=1.0.1",
]